DROP TABLE COMPANY_DEPT
DROP TABLE COMPANY_JOB
DROP TABLE COMPANY_INFO


select * from COMPANY_DEPT;

SELECT * FROM USER_INFO where user_state = 0;

UPDATE USER_INFO
SET USER_DEPT = null
WHERE USER_ID = 'HTA1'

UPDATE USER_INFO
SET USER_state = 2
where user_id = 'micron1'



CREATE TABLE COMPANY_INFO(
    COMPANY_NAME        VARCHAR2(50) PRIMARY KEY,
    COMPANY_URL         VARCHAR2(100),
    COMPANY_LOGO        VARCHAR2(100),
    COMPANY_CSV_FORM    VARCHAR2(100),
    USER_ID             VARCHAR2(30),
	
    FOREIGN KEY (USER_ID) 
    REFERENCES USER_INFO(USER_ID)
    ON DELETE CASCADE
);

CREATE TABLE COMPANY_DEPT
(
    DEPT_NAME VARCHAR2(50),
    COMPANY_NAME VARCHAR2(50)
);

CREATE TABLE COMPANY_JOB
(
    JOB_NAME VARCHAR2(50),
    COMPANY_NAME VARCHAR2(50)
);

INSERT INTO COMPANY_INFO(COMPANY_NAME, COMPANY_URL, USER_ID)
VALUES(
    'CO-WORK1', 'http://cowork.run/', 'HTA1'
);


INSERT INTO COMPANY_DEPT(DEPT_NAME, COMPANY_NAME)
VALUES('개발1팀', 'CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NAME, COMPANY_NAME)
VALUES('개발2팀', 'CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NAME, COMPANY_NAME)
VALUES('개발3팀', 'CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NAME, COMPANY_NAME)
VALUES('영업1팀', 'CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NAME, COMPANY_NAME)
VALUES('인사팀','CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NAME, COMPANY_NAME)
VALUES('기획팀','CO-WORK');


INSERT INTO COMPANY_JOB(JOB_NAME, COMPANY_NAME)
VALUES('대표', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NAME, COMPANY_NAME)
VALUES('사원', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NAME, COMPANY_NAME)
VALUES('대리', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NAME, COMPANY_NAME)
VALUES('과장', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NAME, COMPANY_NAME)
VALUES('차장', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NAME, COMPANY_NAME)
VALUES('부장', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NAME, COMPANY_NAME)
VALUES('상무', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NAME, COMPANY_NAME)
VALUES('이사', 'CO-WORK');