select * from PROJECT;

--테이블 행 삭제
delete from PROJECT;

--테이블 삭제
drop table PROJECT;

--PROJECT_NUM 시퀀스 생성
CREATE SEQUENCE PROJECT_SEQ
INCREMENT BY 1
START WITH 1;

--데이터 삭제 시 시퀀스 -1
ALTER SEQUENCE PROJECT_SEQ INCREMENT BY -1

--시퀀스 삭제
DROP SEQUENCE PROJECT_SEQ

CREATE TABLE PROJECT(
PROJECT_NUM			NUMBER(10) PRIMARY KEY NOT NULL,
PROJECT_NAME			VARCHAR2(100) NOT NULL,
PROJECT_STATE			VARCHAR2(20),
PROJECT_PROG			NUMBER,
PROJECT_START			DATE,
PROJECT_END			DATE,
PROJECT_PRIORITY		VARCHAR2(20),
PROJECT_PARTICI		NUMBER,
PROJECT_ADMIN			VARCHAR2(30) NOT NULL,
PROJECT_BOOKMARK		NUMBER,
FOREIGN KEY(PROJECT_ADMIN) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE
);

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE, PROJECT_PROG,
PROJECT_START, PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트1', '곧 마감', '80',
'2023-01-30', '2023-02-01', 'HTA1');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE, PROJECT_PROG,
PROJECT_START, PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL, '프로젝트2', '진행중', '40',
'2023-02-01', '2023-02-10', 'HTA2');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE, PROJECT_PROG,
PROJECT_START, PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트3', '마감', '80',
'2023-01-01', '2023-01-20', 'HTA3');