select * from PROJECT_BOARD;

--테이블 행 삭제
delete from PROJECT_BOARD;

--PROJECT_NUM 시퀀스 생성
CREATE SEQUENCE PROJECT_BOARD_SEQ
INCREMENT BY 1
START WITH 1;

--데이터 삭제 시 시퀀스 -1
ALTER SEQUENCE PROJECT_SEQ 
INCREMENT BY -2;

SELECT PROJECT_SEQ.NEXTVAL
FROM dual;
 
ALTER SEQUENCE PROJECT_SEQ
INCREMENT BY 1;

--시퀀스 삭제
DROP SEQUENCE PROJECT_BOARD_SEQ

CREATE TABLE PROJECT_BOARD(
PRO_BOARD_NUM			NUMBER(30) PRIMARY KEY NOT NULL, 
PRO_BOARD_CREATER_ID 	VARCHAR2(30) NOT NULL, 
PRO_BOARD_CARTEGORY		VARCHAR2(30) NOT NULL,  
PRO_BOARD_STATE			VARCHAR2(20),  
PRO_BOARD_MANAGER		VARCHAR2(50),
PRO_BOARD_CREATER_NAME VARCHAR2(50) NOT NULL,
PRO_BOARD_SUBJECT 		VARCHAR2(100) NOT NULL, 
PRO_BOARD_CONTENT		VARCHAR2(1000), 
PRO_BOARD_FILE			VARCHAR2(500),
PRO_BOARD_READCOUNT		NUMBER,
PRO_BOARD_CREATE_DATE	DATE,
PRO_BOARD_START			DATE,
PRO_BOARD_END			DATE,
PRO_BOARD_PRIORITY		VARCHAR2(20),
PRO_BOARD_LIKE			NUMBER,
PRO_BOARD_BOOKMARK		NUMBER(2), 
PROJECT_NUM				NUMBER,
FOREIGN KEY(PRO_BOARD_CREATER_ID) REFERENCES USER_INFO(USER_ID)
ON DELETE CASCADE,
FOREIGN KEY(PRO_BOARD_MANAGER) REFERENCES USER_INFO(USER_ID)
ON DELETE CASCADE,
FOREIGN KEY(PROJECT_NUM) REFERENCES PROJECT(PROJECT_NUM) ON DELETE CASCADE
);

INSERT INTO PROJECT_BOARD(
PRO_BOARD_NUM, PRO_BOARD_CREATER_ID, PRO_BOARD_CARTEGORY, PRO_BOARD_CREATER_NAME, 
PRO_BOARD_SUBJECT, PRO_BOARD_CONTENT, PRO_BOARD_CREATE_DATE)
VALUES(PROJECT_BOARD_SEQ.NEXTVAL, 'HTA2', '범주', '홍길동',
'글제목', '글 내용', SYSDATE);

INSERT INTO PROJECT_BOARD(
PRO_BOARD_NUM, PRO_BOARD_CREATER_ID, PRO_BOARD_CARTEGORY, PRO_BOARD_CREATER_NAME, 
PRO_BOARD_SUBJECT, PRO_BOARD_CONTENT, PRO_BOARD_CREATE_DATE)
VALUES(PROJECT_BOARD_SEQ.NEXTVAL, 'HTA3', '범주', '멤버1',
'글제목', '글 내용', SYSDATE);

INSERT INTO PROJECT_BOARD(
PRO_BOARD_NUM, PRO_BOARD_CREATER_ID, PRO_BOARD_CARTEGORY, PRO_BOARD_CREATER_NAME, 
PRO_BOARD_SUBJECT, PRO_BOARD_CONTENT, PRO_BOARD_CREATE_DATE)
VALUES(PROJECT_BOARD_SEQ.NEXTVAL, 'HTA4', '범주', '멤버2',
'글제목', '글 내용', SYSDATE);