SELECT * FROM EMP

DROP TABLE COMPANY_INFO PURGE;
DROP TABLE COMPANY_DEPT PURGE;
DROP TABLE COMPANY_JOB PURGE;


CREATE TABLE COMPANY_INFO
(
    COMPANY_NAME        VARCHAR2(50),
    COMPANY_URL         VARCHAR2(100),
    COMPANY_LOGO        VARCHAR2(100),
    COMPANY_CSV_FORM    VARCHAR2(100),
    USER_ID             VARCHAR2(30),
    
    PRIMARY KEY(COMPANY_NAME)
    FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID) 
    ON DELETE CASCADE 
);

CREATE TABLE COMPANY_DEPT
(
    DEPT_NO NUMBER NOT NULL,
    DEPT_NAME VARCHAR2(50) NOT NULL,
    COMPANY_NAME VARCHAR2(50),
    
    PRIMARY KEY(DEPT_NO)
    FOREIGN KEY(COMPANY_NAME)REFERENCES COMPANY_INFO(COMPANY_NAME) 
    ON DELETE CASCADE
);

CREATE TABLE COMPANY_JOB
(
    JOB_NO NUMBER NOT NULL,
    JOB_NAME VARCHAR2(50) NOT NULL,
    COMPANY_NAME VARCHAR2(50),
    
    PRIMARY KEY(JOB_NO)
    FOREIGN KEY(COMPANY_NAME)REFERENCES COMPANY_INFO(COMPANY_NAME) 
    ON DELETE CASCADE
);

INSERT INTO COMPANY_INFO(COMPANY_NAME, COMPANY_URL, USER_ID)
VALUES(
    'CO-WORK', 'http://cowork.run/', 'HTA1'
);


INSERT INTO COMPANY_DEPT(DEPT_NO, DEPT_NAME, COMPANY_NAME)
VALUES(0101, '개발1팀', 'CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NO, DEPT_NAME, COMPANY_NAME)
VALUES(0102, '개발2팀', 'CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NO, DEPT_NAME, COMPANY_NAME)
VALUES(0103, '개발3팀', 'CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NO, DEPT_NAME, COMPANY_NAME)
VALUES(0201, '영업1팀', 'CO-WORK');
INSERT INTO COMPANY_DEPT(DEPT_NO, DEPT_NAME, COMPANY_NAME)
VALUES(0301, '인사팀','CO-WORK');


INSERT INTO COMPANY_JOB(JOB_NO, JOB_NAME, COMPANY_NAME)
VALUES(1000, '대표', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NO, JOB_NAME, COMPANY_NAME)
VALUES(1001, '사원', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NO, JOB_NAME, COMPANY_NAME)
VALUES(1002, '대리', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NO, JOB_NAME, COMPANY_NAME)
VALUES(1003, '과장', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NO, JOB_NAME, COMPANY_NAME)
VALUES(1004, '차장', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NO, JOB_NAME, COMPANY_NAME)
VALUES(1005, '부장', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NO, JOB_NAME, COMPANY_NAME)
VALUES(1006, '상무', 'CO-WORK');
INSERT INTO COMPANY_JOB(JOB_NO, JOB_NAME, COMPANY_NAME)
VALUES(1007, '이사', 'CO-WORK');