select * from PROJECT;

--테이블 행 삭제
delete from PROJECT;

--PROJECT_NUM 시퀀스 생성
CREATE SEQUENCE PROJECT_SEQ
INCREMENT BY 1
START WITH 1;

--데이터 삭제 시 시퀀스 -1
ALTER SEQUENCE PROJECT_SEQ 
INCREMENT BY -2;

SELECT PROJECT_SEQ.NEXTVAL
FROM dual;
 
ALTER SEQUENCE PROJECT_SEQ
INCREMENT BY 1;

--시퀀스 삭제
DROP SEQUENCE PROJECT_SEQ

CREATE TABLE PROJECT(
PROJECT_NUM	 			NUMBER(10) PRIMARY KEY NOT NULL,
PROJECT_NAME		 	VARCHAR2(100) NOT NULL,
PROJECT_STATE	 		VARCHAR2(20),
PROJECT_PROG	 		NUMBER,
PROJECT_START 			DATE,
PROJECT_END	 			DATE,
PROJECT_PRIORITY 		VARCHAR2(20),
PROJECT_PARTICI	 		NUMBER,
PROJECT_ADMIN	 		VARCHAR2(30),
PROJECT_PARTI	 	 	VARCHAR2(30),
PROJECT_BOOKMARK	 	NUMBER,
FOREIGN KEY(PROJECT_PARTI) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE,
FOREIGN KEY(PROJECT_ADMIN) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE
);

ALTER TABLE PROJECT ADD PROJECT_PARTI varchar(30);

ALTER TABLE PROJECT
ADD CONSTRAINT PARTI_FK
FOREIGN KEY(PROJECT_PARTI) REFERENCES USER_INFO(USER_ID);

ALTER TABLE PROJECT MODIFY (PROJECT_PROG DEFAULT 0);
ALTER TABLE PROJECT MODIFY (PROJECT_PARTICI DEFAULT 0);

UPDATE PROJECT
SET PROJECT_PARTI = 'HTA1';

UPDATE PROJECT
SET PROJECT_PARTICI = 0;

UPDATE PROJECT
SET PROJECT_START = '2023-01-01';

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트1', '곧 마감', 'HTA1');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL, '프로젝트2', '진행중', 'HTA2');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트3', '마감', 'HTA3');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE,PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트4', '진행중','2023-03-14', 'HTA3');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE,PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트5', '곧마감','2023-02-14', 'HTA3');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE,PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트6', '곧마감','2023-02-18', 'HTA3');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE,PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트HTA7', '곧마감','2023-04-18', 'HTA1');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE,PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트HTA7', '곧마감','2023-05-18', 'HTA1');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE,PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트HTA7', '곧마감','2023-05-31', 'HTA1');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE,PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트HTA9', '곧마감','2023-04-10', 'HTA1');

INSERT INTO PROJECT
(PROJECT_NUM, PROJECT_NAME, PROJECT_STATE,PROJECT_END, PROJECT_ADMIN)
VALUES(PROJECT_SEQ.NEXTVAL,'프로젝트HTA9', '곧마감','2023-06-08', 'HTA1');

select * from PROJECT;

DELETE PROJECT;

drop table project purge

SELECT ROWNUM,P.* FROM (SELECT * FROM PROJECT ORDER BY PROJECT_END)P;

SELECT * FROM (SELECT ROWNUM,P.* 
FROM (SELECT * FROM PROJECT ORDER BY PROJECT_END)P WHERE ROWNUM <= 10) WHERE ROWNUM >= 1 AND ROWNUM <=5

commit
