select * from USER_INFO WHERE user_id = 'HTA1';

CREATE TABLE USER_INFO(
	USER_ID		VARCHAR2(30),
	USER_PASSWORD	VARCHAR2(50),
	USER_EMAIL		VARCHAR2(50),
	USER_CODE		NUMBER(10),
	USER_NAME		VARCHAR2(20),
	USER_IMG		VARCHAR2(50),
	USER_IS_ADMIN	NUMBER(2),
	USER_DEPT		VARCHAR2(20),
	USER_JOB		VARCHAR2(20),
	USER_FAX		VARCHAR2(20),
	USER_INTRO		VARCHAR2(600),
	USER_CARD		VARCHAR2(50),
	USER_STATE		NUMBER,
	USER_JOIN_DATE	DATE default sysdate,
	USER_PHONE		VARCHAR2(50),
	PRIMARY KEY(USER_ID)
);


DROP TABLE USER_INFO;


INSERT INTO USER_INFO
(USER_ID, USER_PASSWORD, USER_EMAIL, USER_CODE, USER_NAME)
VALUES('HTA1', '1234', 'hta1@hta.com', '1234', '홍길동');

INSERT INTO USER_INFO
(USER_ID, USER_PASSWORD, USER_EMAIL, USER_CODE, USER_NAME)
VALUES('HTA2', '1234', 'hta2@naver.com', '1234', '멤버1');

INSERT INTO USER_INFO
(USER_ID, USER_PASSWORD, USER_EMAIL, USER_CODE, USER_NAME)
VALUES('HTA3', '1234', 'hta3@naver.com', '1234', '멤버2');

INSERT INTO USER_INFO
(USER_ID, USER_PASSWORD, USER_EMAIL, USER_CODE, USER_NAME)
VALUES('HTA4', '1234', 'hta4@naver.com', '1234', '멤버3');

INSERT INTO USER_INFO
(USER_ID, USER_PASSWORD, USER_EMAIL, USER_CODE, USER_NAME)
VALUES('HTA5', '1234', 'hta5@naver.com', '1234', '멤버4');