--테이블 삭제
DROP TABLE FREE CASCADE CONSTRAINTS PURGE;
--테이블 생성
CREATE TABLE FREE(
		FREE_NUM			NUMBER,						--글 번호
		FREE_NAME			VARCHAR2(30),				--작성자
		FREE_PASS			VARCHAR2(30) NOT NULL,		--비밀번호
		FREE_SUBJECT		VARCHAR2(300) NOT NULL,		--제목
		FREE_CONTENT		VARCHAR2(4000) NOT NULL,	--내용
		FREE_FILE			VARCHAR2(50),				--첨부될 파일 명
		FREE_RE_REF			NUMBER,						--답변 글 작성시 참조되는 글의 번호
		FREE_RE_LEV			NUMBER,						--답변 글의 깊이
		FREE_RE_SEQ			NUMBER,						--답변 글의 순서
		FREE_READCOUNT		NUMBER,						--글의 조회수
		FREE_REG_DATE DATE DEFAULT SYSDATE,				--글의 작성 날짜
		FREE_LIKE			NUMBER,						--좋아요
		FREE_HATE			NUMBER,						--싫어요
		PRIMARY KEY(FREE_NUM)
);


--값 입력
INSERT INTO FREE(FREE_NO, FREE_TITLE, FREE_RRG_DATE, FREE_CONTENT, FREE_PASS)
VALUES(SEQ_FREE_NO.NEXTVAL, '자유게시판1', SYSDATE, '게시판1내용입니다.', '1234')
;
INSERT INTO FREE(FREE_NO, FREE_TITLE, FREE_RRG_DATE, FREE_CONTENT, FREE_PASS)
VALUES(SEQ_FREE_NO.NEXTVAL, '자유게시판2', SYSDATE, '게시판2내용입니다.', '1234')
;
INSERT INTO FREE(FREE_NO, FREE_TITLE, FREE_RRG_DATE, FREE_CONTENT, FREE_PASS)
VALUES(SEQ_FREE_NO.NEXTVAL, '자유게시판3', SYSDATE, '게시판4내용입니다.', '1234')
;

--NOTICE 테이블 조회
SELECT * FROM FREE;