--FREE(자유)
--시퀀스 삭제
DROP SEQUENCE SEQ_FREE_NO
;
--시퀀스 생성
CREATE SEQUENCE SEQ_FREE_NO
INCREMENT BY 1
START WITH 1
ORDER
;

--테이블 삭제
DROP TABLE FREE
;

--테이블 생성
CREATE TABLE FREE(
FREE_NO NUMBER(4) NOT NULL PRIMARY KEY,
FREE_TITLE VARCHAR2(150) NOT NULL,
FREE_RRG_DATE DATE DEFAULT SYSDATE,
FREE_CONTENT VARCHAR2(4000) NOT NULL,
FREE_FILE VARCHAR2(300),
FREE_VIEWS NUMBER(4),
FREE_PASS NUMBER(4) NOT NULL,
FREE_LIKE NUMBER(4),
FREE_DOWN NUMBER(4)
);


--값 입력
INSERT INTO FREE(FREE_NO, FREE_TITLE, FREE_RRG_DATE, FREE_CONTENT, FREE_PASS)
VALUES(SEQ_FREE_NO.NEXTVAL, '자유게시판1', SYSDATE, '게시판1내용입니다.', '1234')
;
INSERT INTO FREE(FREE_NO, FREE_TITLE, FREE_RRG_DATE, FREE_CONTENT, FREE_PASS)
VALUES(SEQ_FREE_NO.NEXTVAL, '자유게시판2', SYSDATE, '게시판2내용입니다.', '1234')
;
INSERT INTO FREE(FREE_NO, FREE_TITLE, FREE_RRG_DATE, FREE_CONTENT, FREE_PASS)
VALUES(SEQ_FREE_NO.NEXTVAL, '자유게시판3', SYSDATE, '게시판4내용입니다.', '1234')
;

--값 삭제
DELETE FROM FREE
WHERE FREE_NO = ?
;

--NOTICE 테이블 조회
SELECT * FROM FREE;