--REPLY(댓글)
--시퀀스 삭제
DROP SEQUENCE SEQ_REPLY_NO
;
--시퀀스 생성
CREATE SEQUENCE SEQ_REPLY_NO
INCREMENT BY 1
START WITH 1
ORDER
;

--시퀀스 삭제
DROP SEQUENCE SEQ_REPLY_NO
;

--테이블 생성
CREATE TABLE REPLY(
REPLY_NO NUMBER(4) NOT NULL PRIMARY KEY,
REPLY_REG_DATE DATE DEFAULT SYSDATE,
REPLY_CONTENT VARCHAR2(2000) NOT NULL,
REPLY_PASS NUMBER(4) NOT NULL,
REPLY_NO NUMBER(4)
--REPLY_LEV NUMBER(4)
--구현한뒤 추가예정
);

--FOREIGN KEY
ALTER TABLE REPLY(
ADD CONSTRAINT FK_FREE_NO FOREIGN KEY(FREE_NO) REFERENCES FREE(FREE_NO)
);

--값 입력
INSERT INTO REPLY(REPLY_NO, REPLY_REG_DATE, REPLY_CONTENT, REPLY_PASS)
VALUES(SEQ_REPLY_NO.NEXTVAL, SYSDATE, '댓글1내용입니다.', '1234')
;
INSERT INTO REPLY(REPLY_NO, REPLY_REG_DATE, REPLY_CONTENT, REPLY_PASS)
VALUES(SEQ_REPLY_NO.NEXTVAL, SYSDATE, '댓글2내용입니다.', '1234')
;
INSERT INTO REPLY(REPLY_NO, REPLY_REG_DATE, REPLY_CONTENT, REPLY_PASS)
VALUES(SEQ_REPLY_NO.NEXTVAL, SYSDATE, '댓글3내용입니다.', '1234')
;

--값 삭제
DELETE FROM REPLY
WHERE REPLY_NO = ?
;

--REPLY 테이블 조회
SELECT * FROM REPLY;