--테이블 삭제
DROP TABLE NOTICE CASCADE CONSTRAINTS PURGE;
--테이블 생성
CREATE TABLE NOTICE(
		NOTICE_NUM			NUMBER,						--글 번호
		NOTICE_NAME			VARCHAR2(30),				--작성자
		NOTICE_SUBJECT		VARCHAR2(300) NOT NULL,		--제목
		NOTICE_CONTENT		VARCHAR2(4000) NOT NULL,	--내용
		NOTICE_FILE			VARCHAR2(50),				--첨부될 파일 명
		NOTICE_RE_REF		NUMBER,						--답변 글 작성시 참조되는 글의 번호
		NOTICE_RE_LEV		NUMBER,						--답변 글의 깊이
		NOTICE_RE_SEQ		NUMBER,						--답변 글의 순서
		NOTICE_READCOUNT	NUMBER,						--글의 조회수
		NOTICE_REG_DATE 	DATE DEFAULT SYSDATE,		--글의 작성 날짜
		PRIMARY KEY(NOTICE_NUM)
);

--값 입력
INSERT INTO NOTICE(NOTICE_NUM, NOTICE_SUBJECT, NOTICE_REG_DATE, NOTICE_CONTENT)
VALUES('1', '공지사항1', SYSDATE, '공지사항1내용입니다.')
;
INSERT INTO NOTICE(NOTICE_NUM, NOTICE_SUBJECT, NOTICE_REG_DATE, NOTICE_CONTENT)
VALUES('2', '공지사항2', SYSDATE, '공지사항2내용입니다.')
;
INSERT INTO NOTICE(NOTICE_NUM, NOTICE_SUBJECT, NOTICE_REG_DATE, NOTICE_CONTENT)
VALUES('3', '공지사항3', SYSDATE, '공지사항3내용입니다.')
;

--NOTICE 테이블 조회
SELECT * FROM NOTICE;