--NOTICE(공지)
--시퀀스 삭제
DROP SEQUENCE SEQ_NOTICE_NO
;
--시퀀스 생성
CREATE SEQUENCE SEQ_NOTICE_NO
INCREMENT BY 1
START WITH 1
ORDER
;

--테이블 삭제
DROP TABLE NOTICE cascade constraints purge;


--테이블 생성
CREATE TABLE NOTICE(
NOTICE_NUM NUMBER(4) NOT NULL,
NOTICE_TITLE VARCHAR2(150) NOT NULL,
NOTICE_REG_DATE DATE DEFAULT SYSDATE,
NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
NOTICE_FILE VARCHAR2(300),
NOTICE_READCOUNT NUMBER(4),
USER_ID VARCHAR2(30),
PRIMARY KEY(NOTICE_NUM)
);

--FOREIGN KEY
ALTER TABLE NOTICE(
ADD CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER_TABLE(USER_ID)
);

--값 입력
INSERT INTO NOTICE(NOTICE_NO, NOTICE_TITLE, NOTICE_REG_DATE, NOTICE_CONTENT)
VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항1', SYSDATE, '공지사항1내용입니다.')
;
INSERT INTO NOTICE(NOTICE_NO, NOTICE_TITLE, NOTICE_REG_DATE, NOTICE_CONTENT)
VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항2', SYSDATE, '공지사항2내용입니다.')
;
INSERT INTO NOTICE(NOTICE_NO, NOTICE_TITLE, NOTICE_REG_DATE, NOTICE_CONTENT)
VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항3', SYSDATE, '공지사항3내용입니다.')
;

--값 삭제
DELETE FROM NOTICE
WHERE NOTICE_NO = ?
;

--NOTICE 테이블 조회
SELECT * FROM NOTICE;